language: generic
services:
  - docker
jobs:
  include:
    - stage: Build
      script:
        - docker pull debian:latest
        - docker run --rm debian:latest echo Hello, world
        - docker run --rm debian:latest date
